### ISSUE TITLE
Failed to install ? 🤔 

### ISSUE THREAD

**Issue by I-Pch** [Benature/obsidian-underline#1]
Hi there 😊 !

I just tried to install the plugin (MacOS Big Sur + Obsidian v0.12.3) but for some reasons, I get an error saying
```
Failed to install plugin "Underline".
```
😕 

Any idea why ? 😊

**Comment by Benature** [comment]
Hello, I've seen others encounter this issue (while they're installing other plugins) when the network is not stable in some cases. Maybe you can check your VPN (if you have), or you can directly download the zip from the release(https://github.com/Benature/obsidian-underline/releases).

**Comment by I-Pch** [comment]
Hi @Benature 😊 !
Thank you for your reply 😊 !

I've tested with and without VPN (which has never been a problem until potentially (🤷‍♀️) now 🤔 ) but nothing worked (I discovered I had the same problem with another plugin too...).
So I followed your suggestion and downloaded the `.zip` file 😊 ... and everything seems to work perfectly 👍 !

**Comment by lethefrost** [comment]
Hi @Benature!  I think I encountered the same problem. I haven't ever had that problem with any other plugin yet. Could there be anything wrong with this one? I have the same operating system and obsidian version as @I-Pch .

**Comment by Benature** [comment]
@lethefrost Thank you! That's true. I figured out that I uploaded the wrong file format in the release pages so that the Obisdian cannot download the plugin. Please try again this time, I have tested it on my machine. Sorry for my mistake!

**Comment by lethefrost** [comment]
> @lethefrost Thank you! That's true. I figured out that I uploaded the wrong file format in the release pages so that the Obisdian cannot download the plugin. Please try again this time, I have tested it on my machine. Sorry for my mistake!

Thank you. The plugin works very well and thank you for the convenience you bring to us.

**Comment by lethefrost** [comment]
Hi @Benature , I found that there could still be something wrong with the installation of this plugin in the integrated plugin manager within Obsidian. Every time it shows the latest version is 1.0.0, but I have 0.0.3 installed. No matter how many times I clicked on the update button, it is still always 0.0.3.

**Comment by Benature** [comment]
Hi @lethefrost , maybe you can uninstall the plugin and reinstall it. Since 0.0.3 is installed manually, I guess there may be some issues that Obsidian cannot solve automatically (like the plugin folder name is different?). 

btw, the feature of 0.0.3 is as same as 1.0.0. (I change the big version just because I was finding why we failed to install it, though it is completely unnecessary😅)

**Comment by I-Pch** [comment]
Hi @Benature 😊 !

I was currently running into the same trouble as @lethefrost (unable to get the updated plugin despite Obsidian telling me it was successfully updated 😇 ) and uninstalling/reinstalling the plugin did the trick for me 😊 !

**Comment by lethefrost** [comment]
> Hi @lethefrost , maybe you can uninstall the plugin and reinstall it. Since 0.0.3 is installed manually, I guess there may be some issues that Obsidian cannot solve automatically (like the plugin folder name is different?).
> 
> btw, the feature of 0.0.3 is as same as 1.0.0. (I change the big version just because I was finding why we failed to install it, though it is completely unnecessary😅)



> Hi @Benature 😊 !
> 
> I was currently running into the same trouble as @lethefrost (unable to get the updated plugin despite Obsidian telling me it was successfully updated 😇 ) and uninstalling/reinstalling the plugin did the trick for me 😊 !

Hi guys, it sounds good. I uninstalled and then reinstalled it, and now it works fine! And very glad to see there are now 56 downloads, instead of previous 0 (which is because it cannot be installed inside of Obsidian before). Seems like people like it!

**Comment by Benature** [comment]
Hey guys, my guess is right, it is the folder name. 

I uninstall the plugin again and manually install 0.0.3 by downloading the `underline.zip` file, unzip it, put it under the `plugins` folder. Note that the plugin folder name is `underline`. Then I upgrade the plugin, like yours, the version number is still 0.0.3. But there is a new folder named `obsidian-underline` (which is the plugin's id) under `plugins` folder. I deleted the old `underline` folder and refresh Obsidian, the version is 1.0.0.

Yeah I'm a bit surprised by the install count, more than I thought haha. Thank you for your like and support! ☺️

and hope no more issue occur to disturb you from using this plugin
