### ISSUE TITLE
Add support for Pandoc underline

### ISSUE THREAD

**Issue by StellarStorm** [Benature/obsidian-underline#11]
Hi @Benature,
Thanks for the great plugin!

I'm doing a lot of writing in Markdown and then converting to different formats (mostly PDF or .docx) with `pandoc` to share with others. Pandoc uses a [different notation](https://pandoc.org/MANUAL.html#underline) for underlines, like this:
`[text to underline].{underline}`.

Would it be possible to add support for this, with possibly a toggle in the plugin settings to chose the underline style?

Cheers!

**Comment by Benature** [comment]
Hi, I would suggest you to install my another plugin "[Text Format](https://github.com/Benature/obsidian-text-format)", which allows to custom to add your prefix and suffix.

In your case, the prefix may be `[` and suffix may be `].{underline}` if I understand correctly.

related issues:
- https://github.com/Benature/obsidian-underline/issues/8
- https://github.com/Benature/obsidian-text-format/issues/30#issuecomment-1229835540
