### ISSUE TITLE
Add feature `<sub></sub>` and `<sup></sup>`

### ISSUE THREAD

**Issue by SolovevAnton** [Benature/obsidian-underline#12]
I used to write chemical formulas, and other stuff that frequently requires `<sub>` and `<sup>` tags.
Is it possible to add to this plugin shortcut for it?

**Comment by Benature** [comment]
I would recommend my another plugin [Text-Format > wrapper](https://github.com/Benature/obsidian-text-format#wrapper) to implement this request by custom setting, refer to https://github.com/Benature/obsidian-text-format/issues/30#issuecomment-1229835540
