### ISSUE TITLE
Doesn't work for words at the end of the line

### ISSUE THREAD

**Issue by KevinSaigon** [Benature/obsidian-underline#4]
Hi, I really like the plugin so far but I've encountered some issues

1. Ctrl + U seems to be a built in undo hotkey in Obsidian, I'm not sure why but Ctrl + U just does not underline things, if I change it to alt + u or something else then it works normally. Does anyone happen to know how to make Ctrl + U work?

2. The plugin isn't working when the text selected is at the end of the line. For example, typed "The quick brown fox" and selected "quick brown" then used the hotkey combinations, everything works as expected. However, if I select "fox" and try, nothing happens.

**Comment by Benature** [comment]
1. Is the build in "undo" is "undo close pane"? What if you change the undo hotkey?

here is my hotkeys setting
![image](https://user-images.githubusercontent.com/35028647/149323585-c5d5babb-26b1-48af-a6d4-98f80ae0ea0e.png)

**Comment by Benature** [comment]
I think it is a problem with live preview

**Comment by Benature** [comment]
It is a problem that get out of range of cursor position, fixed in v1.1.4.
