### ISSUE TITLE
Adding Subscript and Superscript

### ISSUE THREAD

**Issue by ruperlopez** [Benature/obsidian-underline#8]
Hello, 

The underline shortcut works awesome!

It would be great if we can use the same application with other tags such as superscript and subscript, `<sup>` and `<sub>` respectively.

**Comment by Benature** [comment]
The plugin "[Text Format](https://github.com/Benature/obsidian-text-format)" can solve this. The setting can refer to https://github.com/Benature/obsidian-text-format/issues/30#issuecomment-1229835540
